apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-mongodb
  template:
    metadata:
      labels:
        app: chat-mongodb
    spec:
      containers:
      - name: mongodb-pod
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin 
        - name: MONGO_INITDB_ROOT_PASSWORD     
          value: secret
        volumeMounts:
        - name: chat-pv-storage
          mountPath: /data/db
      volumes:
      - name: chat-pv-storage
        persistentVolumeClaim:
          claimName: chat-pvc
              